### ISSUE TITLE
Could not figure out how to install the dependencies...

### ISSUE THREAD

**Issue by Mr-Ventures** [mikepowell/streamdeck-commandline#2]
Hello could you please add steps to the installation guide to cover how to install the dependencies you mentioned? I got your plugin installed but I think I need to somehow install the dependencies to get it running.

**Comment by mikepowell** [comment]
Sorry, in hindsight "Dependencies" was a poor choice for the heading. It should probably be "Acknowledgements" instead. In any case you do not need to install these in order to use the plugin. Just download the `.streamDeckPlugin` file from the [Releases page](https://github.com/mikepowell/streamdeck-commandline/releases/tag/v1.1) for this repo, then double-click to open it in the Stream Deck app.

The Stream Deck app _is_ a requirement, if you don't have it installed you can find it [here](https://www.elgato.com/en/downloads).
